# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '1'

steps:
- script: dotnet build --configuration $(buildConfiguration) DotNet.Tracing.Middleware/
  displayName: 'dotnet build $(buildConfiguration)'
- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'DotNet.Tracing.Middleware/*.csproj'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(Major)'
    minorVersion: '$(Minor)'
    patchVersion: '$(rev:.r)'